package com.dairyapplication.dairyApplication.service;

import com.dairyapplication.dairyApplication.dto.FarmerFoodDistributionsDto;
import com.dairyapplication.dairyApplication.entity.FarmerFoodDistributions;

public interface FarmerFoodDistributionsIface {
FarmerFoodDistributions createFarmerFoodDistribution(FarmerFoodDistributionsDto farmerFoodDistributionsDto);
}
